site_name: usethis Documentation

nav:
  - Introduction: index.md
  - Getting Started:
    - Installation: start/installation.md
    - Example Usage: start/example-usage.md
    - Detailed Example: start/detailed-example.md
  - CLI Reference:
    - Overview: cli/overview.md
    - Reference: cli/reference.md
  - With Other Frameworks: frameworks.md
  - Similar Projects: similar-projects.md
  - FAQ: faq.md
  - License: about-license.md

theme:
  name: material
  logo: logo.svg
  favicon: favicon.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-6
        name: Switch between light and dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-6
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/usethis-python/usethis-python
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/usethis/

plugins:
  - search
    